apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-docs
  description: test-docs
  tags:
    - $text: .version
    - group:default/latam
  links:
    - url: https://github.com/xAlstrat/test-docs
      title: Test Docs
      icon: bitbucket
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: me
  system: test-docs
--- # Do Not remove this line
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: product-name
  description: data product description
  annotations:
    backstage.io/techdocs-ref: dir:./data-product-docs
  tags:
    - group:default/latam
spec:
  owner: me